language: node_js
node_js:
  - '4.4.3'
services:
  - mongodb
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.8
      - g++-4.8
env:
  - CXX=g++-4.8 NODE_ENV=test
sudo: required
before_script:
  - npm i -g eslint mocha
  - sleep 10
script:
  - npm test
  - npm run lint
